### ISSUE TITLE
CustomerID

### ISSUE THREAD

**Issue by trindium** [znuny/Znuny4OTRS-CustomerMap#4]
HI All,  Thanks for this and all Awesome plugins... they are really great.

Just Wondering if there is a way to put the CustumerID on the google Map item.

Thanks in advance
Juan

**Comment by thorsteneckel** [comment]
Hi Juan,

thanks for your feedback! Glad to you like our Znuny4OTRS packages :)

In the current version there is no way to present the CustomerID on the GoogleMap item without touching the code. But since it's open source you can do it your own via changing the following file in your System:
https://github.com/znuny/Znuny4OTRS-CustomerMap/blob/master/var/httpd/htdocs/js/Core.Agent.CustomerMap.js#L138

Just add the following block like this:
```JavaScript
...
                        if ( ObjectRef['UserCustomerID'] ) {
                            Content = Content + '<br/>' +  ObjectRef['UserCustomerID'];
                        }
                        if (Address) {
...
```

After that please clear your Loader cache via ```otrs.LoaderCache.pl -o delete``` and clear your Browser cache, too.

Hope this helps.

Best regards,
  Thorsten

**Comment by trindium** [comment]
Thorsten, Thanks, worked like a charm....  

:D
